import pickle
import torch
import numpy as np
from music21 import stream, note, chord, instrument
from model import MusicLSTM

def generate_music():
    print("Loading data...")
    with open('data.pkl', 'rb') as f:
        data = pickle.load(f)
        
    network_input = data['network_input']
    pitches = data['pitches']
    n_vocab = data['n_vocab']
    note_to_int = data['note_to_int']
    
    int_to_note = dict((number, note) for number, note in enumerate(pitches))
    
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Using device: {device}")
    
    model = MusicLSTM(n_vocab=n_vocab)
    model.load_state_dict(torch.load('music_model.pth', map_location=device))
    model = model.to(device)
    model.eval()
    
    # Pick a random sequence from the input as a starting point for the generation
    start = np.random.randint(0, len(network_input)-1)
    pattern = network_input[start].tolist()
    
    prediction_output = []
    
    print("Generating notes...")
    # generate 100 notes
    for note_index in range(100):
        input_sequence = torch.tensor(pattern, dtype=torch.long).unsqueeze(0).to(device)
        
        with torch.no_grad():
            prediction = model(input_sequence)
            
        # Get the predicted integer
        # We can also add temperature sampling here for more variety
        probs = torch.softmax(prediction, dim=1).squeeze().cpu().numpy()
        
        # sample using temperature
        temperature = 1.0
        preds = np.log(probs + 1e-7) / temperature
        exp_preds = np.exp(preds)
        preds = exp_preds / np.sum(exp_preds)
        
        index = np.random.choice(len(preds), p=preds)
        
        result = int_to_note[index]
        prediction_output.append(result)
        
        pattern.append(index)
        pattern = pattern[1:len(pattern)]
        
    print("Creating MIDI file...")
    
    offset = 0
    output_notes = []
    
    # create note and chord objects based on the values generated by the model
    for pattern in prediction_output:
        # pattern is a chord
        if ('.' in pattern) or pattern.isdigit():
            notes_in_chord = pattern.split('.')
            notes = []
            for current_note in notes_in_chord:
                new_note = note.Note(int(current_note))
                new_note.storedInstrument = instrument.Piano()
                notes.append(new_note)
            new_chord = chord.Chord(notes)
            new_chord.offset = offset
            output_notes.append(new_chord)
        # pattern is a note
        else:
            new_note = note.Note(pattern)
            new_note.offset = offset
            new_note.storedInstrument = instrument.Piano()
            output_notes.append(new_note)
            
        # increase offset each iteration so that notes do not stack
        offset += 0.5
        
    midi_stream = stream.Stream(output_notes)
    midi_stream.write('midi', fp='generated_music.mid')
    print("Generated music saved to generated_music.mid")

if __name__ == '__main__':
    generate_music()
